#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: The Box Project
org_Mission: > Create a better tomorrow, make a difference today!
  
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  The Box Project offers a unique opportunity to give back. We are distinct because we create supportive, personal relationships directly between a sponsor family and a family in need living in rural America. The Box Project acts as matchmaker, pairing our “sponsor” volunteers with carefully screened individuals or families that need help. The sponsors offer long term, meaningful interactions including encouragement, advice, and boxes of needed supplies about once a month. 
#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: info@boxproject.org
org_street_address: 315 Losher Street 
org_address_suite: Suite 100
org_city: Hernando
org_state: Ms
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  38632
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  Office Phone: 1-662-449-5002
  Toll Free Phone: 1-800-268-9928
  Fax: 1-662-449-5006

#SOCIAL MEDIA
org_twitter_username: http://www.twitter.com/@TBP1962
org_facebook_username: https://www.facebook.com/TBP1962/
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
